#!/bin/sh
ar x sublime.deb
rm -f sublime.deb
tar xf data.tar.lzma
rm -f control.tar.gz data.tar.lzma debian-binary
mv usr/* .
rmdir usr
mkdir -p export/share/applications
sed s/Icon=sublime-text/Icon=com.sublimetext.Sublime/ share/applications/sublime_text.desktop > export/share/applications/com.sublimetext.Sublime.desktop
mkdir -p export/share/icons/hicolor/256x256/apps
cp share/icons/hicolor/256x256/apps/sublime-text.png export/share/icons/hicolor/256x256/apps/com.sublimetext.Sublime.png
